<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>fr.becpg</groupId>
		<artifactId>alfresco-patch</artifactId>
		<version>26.1.0.50-SNAPSHOT</version>
		<relativePath>../</relativePath>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>alfresco-core</artifactId>
	<name>Alfresco core Patch</name>
	
	
	
	<dependencies>
		<dependency>
			<groupId>org.alfresco</groupId>
			<artifactId>alfresco-core</artifactId>
			<version>${alfresco-core.version}</version>
			<scope>compile</scope>
		</dependency>
        
	</dependencies>
	<build>
		<finalName>${project.artifactId}-${alfresco-core.version}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<promoteTransitiveDependencies>false</promoteTransitiveDependencies>
							<shadedArtifactAttached>false</shadedArtifactAttached>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<artifactSet>
								<includes>
									<include>org.alfresco:alfresco-core</include>
								</includes>
							</artifactSet>
							<filters>
								<filter>
									<artifact>org.alfresco:alfresco-core</artifact>
									<excludes>
										<exclude>org/alfresco/util/transaction/TransactionSupportUtil**</exclude>
									</excludes>
								</filter>
								<filter>
									<artifact>fr.becpg:alfresco-core</artifact>
									<excludes>
										<exclude>META-INF/MANIFEST.MF</exclude>
									</excludes>
								</filter>
								<filter>
									<artifact>fr.becpg:alfresco-core</artifact>
									<excludes>
										<exclude>META-INF/MANIFEST.MF</exclude>
									</excludes>
								</filter>
							</filters>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
