/*******************************************************************************
 * Copyright (C) 2010-2017 beCPG. 
 *  
 * This file is part of beCPG 
 *  
 * beCPG is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU Lesser General Public License as published by 
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *  
 * beCPG is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU Lesser General Public License for more details. 
 *  
 * You should have received a copy of the GNU Lesser General Public License along with beCPG. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package fr.becpg.repo.search.lucene.analysis;

/**
 * @author nicolasr
 * créé le 23 juil. 2003
 */
public interface FrenchStopWords {
    String[] STOP_WORDS =
        {
			"a",
            "au",
            "aux",
            "avec",
            "ce",
            "ces",
            "dans",
            "de",
            "des",
            "du",
            "elle",
            "en",
            "et",
            "eux",
            "il",
            "je",
            "la",
            "le",
            "leur",
            "lui",
            "ma",
            "mais",
            "me",
            "même",
            "mes",
            "moi",
            "mon",
            "ne",
            "nos",
            "notre",
            "nous",
            "on",
            "ou",
            "par",
            "pas",
            "pour",
            "qu",
            "que",
            "qui",
            "sa",
            "se",
            "ses",
            "son",
            "sur",
            "ta",
            "te",
            "tes",
            "toi",
            "ton",
            "tu",
            "un",
            "une",
            "vos",
            "votre",
            "vous",
            "c",
            "d",
            "j",
            "l",
            "à",
            "m",
            "n",
            "s",
            "t",
            "y",
            "été",
            "étés",
            "suis",
            "es",
            "est",
            "sommes",
            "êtes",
            "sont",
            "serai",
            "seras",
            "sera",
            "serons",
            "serez",
            "seront",
            "serais",
            "serait",
            "serions",
            "seriez",
            "seraient",
            "étais",
			"etre",
            "était",
            "étions",
            "étiez",
            "étaient",
            "fus",
            "fut",
            "fûmes",
            "fûtes",
            "furent",
            "sois",
            "soit",
            "soyons",
            "soyez",
            "soient",
            "fusse",
            "fusses",
            "fût",
            "fussions",
            "fussiez",
            "fussent",
            "ayant",
            "ayante",
            "ayantes",
            "ayants",
            "eu",
            "eue",
            "eues",
            "eus",
            "ai",
            "as",
            "avons",
            "avez",
            "ont",
            "aurai",
            "auras",
            "aura",
            "aurons",
            "aurez",
            "auront",
            "aurais",
            "aurait",
            "aurions",
            "auriez",
            "auraient",
            "avais",
            "avait",
            "avions",
            "aviez",
            "avaient",
            "eut",
            "eûmes",
            "eûtes",
            "eurent",
            "aie",
            "aies",
            "ait",
            "ayons",
            "ayez",
            "aient",
            "eusse",
            "eusses",
            "eut",
            "eussions",
            "eussiez",
            "eussent" };
}
