version: '3'
services:
  becpg:
    environment:
      CATALINA_OPTS: "-Xmx4G -XX:HotswapAgent=external -Duser.language=fr -Duser.country=FR 
                      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888 
                      -XX:HotswapAgent=fatjar
                      -XX:+UseG1GC
                      -Dcom.sun.management.jmxremote.rmi.port=9091
                      -Dcom.sun.management.jmxremote=true
                      -Dcom.sun.management.jmxremote.port=9091
                      -Dcom.sun.management.jmxremote.ssl=false
                      -Dcom.sun.management.jmxremote.authenticate=false
                      -Dcom.sun.management.jmxremote.local.only=false
                      -Djava.rmi.server.hostname=127.0.0.1"
#      JAVA_HOME : "/usr/lib/jvm/java"
#      CATALINA_OPTS: "-Xmx4G -Duser.language=fr -Duser.country=FR 
#                      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888 
#                      -XX:+FlightRecorder
#                      -XX:+UseG1GC
#                      -Dcom.sun.management.jmxremote.rmi.port=9091
#                      -Dcom.sun.management.jmxremote=true
#                      -Dcom.sun.management.jmxremote.port=9091
#                      -Dcom.sun.management.jmxremote.ssl=false
#                      -Dcom.sun.management.jmxremote.authenticate=false
#                      -Dcom.sun.management.jmxremote.local.only=false
#                      -Djava.rmi.server.hostname=127.0.0.1"                      

