
becpg.group.aiuser                    = beCPG AI Users
becpg.group.apiconnector              = API Connectors
becpg.group.externaluser              = beCPG External Users
becpg.group.externalusermgr           = beCPG External Users Managers
becpg.group.languagemgr               = beCPG Language managers
becpg.group.licensereadconcurrent     = Concurrent read licence
becpg.group.licensereadnamed          = Named read licence
becpg.group.licensesupplierconcurrent = Supplier concurrent licence
becpg.group.licensewriteconcurrent    = Concurrent write licence
becpg.group.licensewritenamed         = Named write licence
becpg.group.olapuser                  = beCPG Olap Users
becpg.group.savedsearchmgr            = beCPG Saved searches managers
becpg.group.securityrole              = beCPG Security roles
becpg.group.specialuser               = System account
becpg.group.nolicense                 = No license
becpg.group.systemmgr                 = beCPG System managers
