-- ----------------------------------------------------------------------
-- MySQL Migration Toolkit
-- SQL Create Script
-- ----------------------------------------------------------------------

SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `CIQUAL`
  CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `CIQUAL`;
-- -------------------------------------
-- Tables

DROP TABLE IF EXISTS `CIQUAL`.`COMPILED_DATA`;
CREATE TABLE `CIQUAL`.`COMPILED_DATA` (
  `ORIGFDCD` INT(10) NOT NULL,
  `ORIGCPCD` INT(10) NOT NULL,
  `UNIT` VARCHAR(10) NULL,
  `SELVAL` VARCHAR(10) NULL,
  `MIN` DOUBLE(15, 5) NULL,
  `MAX` DOUBLE(15, 5) NULL,
  `N` DOUBLE(15, 5) NULL,
  `CONFCD` VARCHAR(1) NULL,
  PRIMARY KEY (`ORIGFDCD`, `ORIGCPCD`),
  INDEX `COMPILED_DATAORIGCPCD` (`ORIGCPCD`),
  INDEX `COMPONENTCOMPILED_DATA` (`ORIGCPCD`),
  INDEX `FOODCOMPILED_DATA` (`ORIGFDCD`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CIQUAL`.`COMPONENT`;
CREATE TABLE `CIQUAL`.`COMPONENT` (
  `ORIGCPCD` INT(10) NOT NULL,
  `ECOMPID` VARCHAR(10) NULL,
  `ORIGCPNM` VARCHAR(250) NULL,
  `C_ORIGCPNMABR` VARCHAR(80) NULL,
  `ENGCPNAM` VARCHAR(250) NULL,
  `C_ENGCPNAMABR` VARCHAR(80) NULL,
  PRIMARY KEY (`ORIGCPCD`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CIQUAL`.`DATASET_SOURCES`;
CREATE TABLE `CIQUAL`.`DATASET_SOURCES` (
  `SOURCID` INT(10) NOT NULL AUTO_INCREMENT,
  `ORIGFDCD` INT(10) NULL,
  `ORIGCPCD` INT(10) NULL,
  `ORIGREFCD` INT(10) NULL,
  PRIMARY KEY (`SOURCID`),
  INDEX `{230CE57D-183E-4F03-86F9-B96BF1` (`ORIGCPCD`),
  INDEX `{4714629E-0749-47DA-AA2A-F2D5A1` (`ORIGREFCD`),
  INDEX `SOURCESORIGCPCD` (`ORIGCPCD`),
  INDEX `SOURCESORIGFDCD` (`ORIGFDCD`),
  INDEX `SOURCESORIGREFCD` (`ORIGREFCD`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CIQUAL`.`FOOD`;
CREATE TABLE `CIQUAL`.`FOOD` (
  `ORIGFDCD` INT(10) NOT NULL,
  `ORIGFDNM` VARCHAR(250) NULL,
  `ENGFDNAM` VARCHAR(250) NULL,
  `SCINAM` VARCHAR(250) NULL,
  `ORIGGPCD` VARCHAR(4) NULL,
  `NCF` DOUBLE(7, 2) NULL,
  `FACF` DOUBLE(7, 2) NULL,
  PRIMARY KEY (`ORIGFDCD`),
  INDEX `{17588530-4AC0-4EB7-923C-542B76` (`ORIGGPCD`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CIQUAL`.`FOOD_GROUPS`;
CREATE TABLE `CIQUAL`.`FOOD_GROUPS` (
  `ORIGGPCD` VARCHAR(4) NOT NULL,
  `ORIGGPFR` VARCHAR(50) NULL,
  `ORIGGPENG` VARCHAR(50) NULL,
  PRIMARY KEY (`ORIGGPCD`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CIQUAL`.`FOOD_LANGUAL`;
CREATE TABLE `CIQUAL`.`FOOD_LANGUAL` (
  `ORIGFDCD` INT(10) NOT NULL,
  `LANGL` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ORIGFDCD`, `LANGL`),
  INDEX `{0E5567FD-A684-42C5-ADD6-7CC9AE` (`ORIGFDCD`),
  INDEX `FOOD_LANGUALLANGL` (`LANGL`),
  INDEX `FOOD_LANGUALORIGFDCD` (`ORIGFDCD`),
  INDEX `THS_LanguaLFOOD_LANGUAL` (`LANGL`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CIQUAL`.`REFERENCE`;
CREATE TABLE `CIQUAL`.`REFERENCE` (
  `ORIGREFCD` INT(10) NOT NULL,
  `CITATION` VARCHAR(250) NULL,
  PRIMARY KEY (`ORIGREFCD`)
)
ENGINE = INNODB;

DROP TABLE IF EXISTS `CIQUAL`.`THS_LANGUAL`;
CREATE TABLE `CIQUAL`.`THS_LANGUAL` (
  `Code` VARCHAR(10) NOT NULL,
  `Term` VARCHAR(150) NULL,
  `Term-fr` VARCHAR(150) NULL,
  PRIMARY KEY (`Code`),
  INDEX `THS_LANGUALLANGL` (`Code`)
)
ENGINE = INNODB;



SET FOREIGN_KEY_CHECKS = 1;

-- ----------------------------------------------------------------------
-- EOF

