SLabel.tableOfContents = TABLE OF CONTENTS
SLabel.productName = TECHNICAL SPECIFICATIONS OF THE ITEM
SLabel.specificationSheet = TECHNICAL SPECIFICATIONS
SLabel.annexRawMaterials = ANNEX 1: TECHNICAL SPECIFICATIONS - RAW MATERIALS
SLabel.annexRawMaterialsEmptyPlaceholder = Raw materials specifications to be annexed
SLabel.annexPrimaryPackaging = ANNEX 2: TECHNICAL SPECIFICATIONS - PRIMARY PACKAGING
SLabel.annexPrimaryPackagingEmptyPlaceholder = Primary packaging specifications to be annexed
SLabel.annexSecondaryPackaging = ANNEX 3: TECHNICAL SPECIFICATIONS - SECONDARY PACKAGING
SLabel.annexSecondaryPackagingEmptyPlaceholder = Secondary packaging specifications to be annexed
SLabel.annexPhotos = ANNEX 4: PHOTOS
SLabel.annexPhotosEmptyPlaceholder = To be annexed after the first manufacturing
SLabel.annexQualityDocuments = ANNEX 5: QUALITY DOCUMENTS
SLabel.annexQualityDocumentsEmptyPlaceholder = Quality documents to be annexed
SLabel.annexSubcontractors = ANNEX 6: LIST OF THE AUTHORISED SUBCONTRACTOR
SLabel.annexSubcontractorsEmptyPlaceholder = Subcontractors list to be annexed
