<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>fr.becpg</groupId>
		<artifactId>alfresco-patch</artifactId>
		<version>26.1.0.50-SNAPSHOT</version>
		<relativePath>../</relativePath>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>alfresco-repository</artifactId>
	<name>Alfresco repository Patch</name>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<dependencies>
		<!-- alfresco -->
		<dependency>
			<groupId>org.alfresco</groupId>
			<artifactId>alfresco-repository</artifactId>
			<scope>compile</scope>
		</dependency>
		
		 <dependency>
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
                <scope>provided</scope>
          </dependency>
	</dependencies>
	<build>
		<finalName>${project.artifactId}-${alfresco-repository.version}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<promoteTransitiveDependencies>false</promoteTransitiveDependencies>
							<shadedArtifactAttached>false</shadedArtifactAttached>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<artifactSet>
								<includes>
									<include>org.alfresco:alfresco-repository</include>
									<include>org.alfresco:alfresco-data-model</include>
								</includes>
							</artifactSet>
							<filters>
								<filter>
									<artifact>org.alfresco:alfresco-repository</artifact>
									<excludes>
										<exclude>org/alfresco/repo/forms/processor/node/TypeFormProcessor**</exclude>
										<exclude>org/alfresco/repo/forms/processor/node/ContentModelFormProcessor**</exclude>
										<exclude>org/alfresco/repo/workflow/WorkflowNotificationUtils**</exclude>
										<exclude>org/alfresco/repo/workflow/activiti/tasklistener/TaskNotificationListener**</exclude>
										<exclude>org/alfresco/repo/workflow/activiti/script/ActivitiScriptBase**</exclude>
										<exclude>org/alfresco/repo/forum/CommentServiceImpl**</exclude>
										<exclude>org/alfresco/repo/node/integrity/AssocSourceMultiplicityIntegrityEvent**</exclude>
										<exclude>org/alfresco/repo/node/getchildren/GetChildrenCannedQuery**</exclude>
										<exclude>org/alfresco/repo/security/sync/ChainingUserRegistrySynchronizer**</exclude>
										<exclude>org/alfresco/repo/security/sync/ldap/LDAPUserRegistry**</exclude>
										<exclude>org/alfresco/repo/action/executer/MailActionExecuter**</exclude>
										<exclude>org/alfresco/repo/action/executer/ScriptActionExecuter**</exclude>
										<exclude>org/alfresco/repo/activities/feed/FeedTaskProcessor**</exclude>
										<exclude>org/alfresco/repo/activities/feed/EmailUserNotifier**</exclude>
										<exclude>org/alfresco/repo/activities/feed/RepoCtx**</exclude>
										<exclude>org/alfresco/repo/rendition/RenditionServiceImpl**</exclude>
										<exclude>org/alfresco/repo/rendition/RenditionNodeManager**</exclude>
										<exclude>org/alfresco/repo/thumbnail/ThumbnailRegistry**</exclude>
										<exclude>org/alfresco/repo/search/impl/querymodel/impl/db/functions/DBFTSRange**</exclude>
										<exclude>org/alfresco/repo/search/impl/querymodel/impl/db/functions/DBFTSTerm**</exclude>
										<exclude>org/alfresco/repo/search/impl/querymodel/impl/db/functions/DBFTSPhrase**</exclude>
										<exclude>org/alfresco/repo/security/authentication/identityservice/IdentityServiceRemoteUserMapper**</exclude>
										<exclude>org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponent**</exclude>
										<exclude>org/alfresco/repo/domain/permissions/AclDAOImpl**</exclude>
										<exclude>org/alfresco/repo/domain/permissions/ADMAccessControlListDAO**</exclude>
										<exclude>org/alfresco/repo/domain/solr/NodeParametersEntity**</exclude>
										<exclude>org/alfresco/repo/solr/SOLRTrackingComponentImpl**</exclude>
										<exclude>org/alfresco/repo/preference/PreferenceServiceImpl**</exclude>
										<exclude>org/alfresco/repo/site/SiteServiceImpl**</exclude>
										<exclude>org/alfresco/repo/invitation/site/InviteNominatedSender**</exclude>
										<exclude>org/alfresco/repo/i18n/MessageServiceImpl**</exclude>
										<exclude>org/alfresco/util/DatabaseMetaDataHelper**</exclude>
										<exclude>org/alfresco/repo/nodelocator/XPathNodeLocator**</exclude>
										<exclude>org/alfresco/repo/domain/node/AbstractNodeDAOImpl**</exclude>
										<exclude>org/alfresco/repo/domain/qname/AbstractQNameDAOImpl**</exclude>
										<exclude>org/alfresco/repo/tenant/MultiTAdminServiceImpl**</exclude>
									</excludes>
								</filter>
								<filter>
									<artifact>org.alfresco:alfresco-data-model</artifact>
									<excludes>
										<exclude>org/alfresco/repo/dictionary/DictionaryDAOImpl**</exclude>
										<exclude>org/alfresco/repo/dictionary/AbstractDictionaryRegistry**</exclude>
									</excludes>
								</filter>
								<filter>
									<artifact>fr.becpg:alfresco-repository</artifact>
									<excludes>
										<exclude>META-INF/MANIFEST.MF</exclude>
									</excludes>
								</filter>
								<filter>
									<artifact>fr.becpg:alfresco-repository</artifact>
									<excludes>
										<exclude>META-INF/MANIFEST.MF</exclude>
									</excludes>
								</filter>
							</filters>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
