
header.version-graph=Versions graph

label.compare=Compare
label.noComment=No comment
label.filter-by-name=Filter by name
label.all-states=All states
button.view.simple=Simple view
button.view.detailed=Detailed view

filter.Archived=Archived
filter.Cancelled=Cancelled
filter.Completed=Completed
filter.Compliant=Compliant
filter.InProgress=In progress
filter.NonCompliant=Non compliant
filter.OnHold=On hold
filter.Planned=Planned
filter.Refused=Refused
filter.Simulation=Simulation
filter.Stopped=Stopped
filter.ToValidate=To validate
filter.Valid=Valid
filter.analysis=Analysis
filter.classification=Classification
filter.closed=Closed
filter.closing=Closing
filter.new=New
filter.response=Response
filter.treatment=Treatment

message.noVersions=No versions
