
header.version-graph = Versions graph

label.compare                           = Compare
label.noComment                         = No comment
label.versions-graph-filter-view-full   = Full
label.versions-graph-filter-view-simple = Simple

listconstraint.bcpg_systemState.Archived                    = Archived
listconstraint.bcpg_systemState.Refused                     = Refused
listconstraint.bcpg_systemState.Simulation                  = Simulation
listconstraint.bcpg_systemState.Stopped                     = Stopped
listconstraint.bcpg_systemState.ToValidate                  = To validate
listconstraint.bcpg_systemState.Valid                       = Valid

message.noVersions = No versions
